### ISSUE TITLE
Improve signature verification for votes / proposals

### ISSUE THREAD

**Issue by astro3710** [LionGovIO/LionGov#2]
Right now we're just signing the vote value, we should sign more stuff than that.
Consider having the server sending the client a hash salt (which is also stored inthe votes table), i think this may improve security but i don't know.  so could sign on (hash salt + voteClass + walletAddress + voteValue). The hash salt could be unecesssary though, could add later I guess.

**Comment by astro3710** [comment]
also we should improve signature verification for proposals as well

**Comment by imsys** [comment]
I added Proposal Id + Vote Value + Timestamp, and made the timestamp valid for 5 minutes. That should do the trick!

Proposal Submission: b401b0f2db5e27c03a13a9b74938e514636ec493 
Vote Submission: 7951b39b52b67bc1b24a88d4bcaba20f99f6f5b0
